TARGET = wizard_basic_4
CONFIG += console
CONFIG -= qt
HEADERS += \
	source/thewizardplusplus/utils/Version.h \
	source/thewizardplusplus/utils/StringUtils.h \
	source/thewizardplusplus/utils/StringSide.h \
	source/thewizardplusplus/utils/StringList.h \
	source/thewizardplusplus/utils/StringConverterHelper.h \
	source/thewizardplusplus/utils/StringConverter.h \
	source/thewizardplusplus/utils/os.h \
	source/thewizardplusplus/utils/FormatterTextAlign.h \
	source/thewizardplusplus/utils/Formatter.h \
	source/thewizardplusplus/utils/FileInfo.h \
	source/thewizardplusplus/utils/ConsoleMessageType.h \
	source/thewizardplusplus/utils/Console.h \
	source/thewizardplusplus/utils/CommandLineArguments.h \
	source/thewizardplusplus/utils/exceptions/NullPointerToCommandLineArgument.h \
	source/thewizardplusplus/utils/exceptions/NullPointerToArrayOfCommandLineArguments.h \
	source/thewizardplusplus/utils/exceptions/InvalidNumberOfCommandLineArguments.h \
	source/thewizardplusplus/wizard-basic-4/StatementCompiler.h \
	source/thewizardplusplus/wizard-basic-4/PreprocessorManager.h \
	source/thewizardplusplus/wizard-basic-4/Preprocessor.h \
	source/thewizardplusplus/wizard-basic-4/OperatorList.h \
	source/thewizardplusplus/wizard-basic-4/OperatorAssociativity.h \
	source/thewizardplusplus/wizard-basic-4/Operator.h \
	source/thewizardplusplus/wizard-basic-4/LineTrimmer.h \
	source/thewizardplusplus/wizard-basic-4/LetStatement.h \
	source/thewizardplusplus/wizard-basic-4/LanguageElements.h \
	source/thewizardplusplus/wizard-basic-4/LabelStatement.h \
	source/thewizardplusplus/wizard-basic-4/IfStatement.h \
	source/thewizardplusplus/wizard-basic-4/GoToStatement.h \
	source/thewizardplusplus/wizard-basic-4/GnuAssembler.h \
	source/thewizardplusplus/wizard-basic-4/FunctionCallStatement.h \
	source/thewizardplusplus/wizard-basic-4/ExpressionCompiler.h \
	source/thewizardplusplus/wizard-basic-4/EndStatement.h \
	source/thewizardplusplus/wizard-basic-4/EmptyLineDeleter.h \
	source/thewizardplusplus/wizard-basic-4/DefineStatement.h \
	source/thewizardplusplus/wizard-basic-4/DeclareFunctionStatement.h \
	source/thewizardplusplus/wizard-basic-4/current_version.h \
	source/thewizardplusplus/wizard-basic-4/CompilerConsoleParameters.h \
	source/thewizardplusplus/wizard-basic-4/Compiler.h \
	source/thewizardplusplus/wizard-basic-4/CommentDeleter.h \
	source/thewizardplusplus/wizard-basic-4/CodeLines.h \
	source/thewizardplusplus/wizard-basic-4/AssemblerModule.h \
	source/thewizardplusplus/wizard-basic-4/AssemblerMnemonic.h \
	source/thewizardplusplus/wizard-basic-4/AssemblerCode.h \
	source/thewizardplusplus/wizard-basic-4/Assembler.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownStatement.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownExpressionToken.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownCommandLineOption.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UndefinedVariable.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UndefinedFunction.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnableToOpenSourceFile.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/SeparatorNotFound.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedOpeningBracket.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedFunctionArgumentSeparatorOrOpeningBracket.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedClosingBracket.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/LabelConflictWithOtherLabel.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/LabelConflictWithConditionalJumps.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidStringFormat.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidNumberOfCodeLineParts.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidFunctionIdentifier.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/IfWithoutEnd.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/IdentifierConflictWithVariable.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/IdentifierConflictWithFunction.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/EndWithoutIf.h \
	source/thewizardplusplus/wizard-basic-4/exceptions/CompileException.h
SOURCES += \
	source/thewizardplusplus/utils/StringUtils.cpp \
	source/thewizardplusplus/utils/StringList.cpp \
	source/thewizardplusplus/utils/StringConverterHelper.cpp \
	source/thewizardplusplus/utils/Formatter.cpp \
	source/thewizardplusplus/utils/FileInfo.cpp \
	source/thewizardplusplus/utils/Console.cpp \
	source/thewizardplusplus/utils/CommandLineArguments.cpp \
	source/thewizardplusplus/utils/exceptions/NullPointerToCommandLineArgument.cpp \
	source/thewizardplusplus/utils/exceptions/NullPointerToArrayOfCommandLineArguments.cpp \
	source/thewizardplusplus/utils/exceptions/InvalidNumberOfCommandLineArguments.cpp \
	source/thewizardplusplus/wizard-basic-4/StatementCompiler.cpp \
	source/thewizardplusplus/wizard-basic-4/PreprocessorManager.cpp \
	source/thewizardplusplus/wizard-basic-4/Preprocessor.cpp \
	source/thewizardplusplus/wizard-basic-4/OperatorList.cpp \
	source/thewizardplusplus/wizard-basic-4/Operator.cpp \
	source/thewizardplusplus/wizard-basic-4/main.cpp \
	source/thewizardplusplus/wizard-basic-4/LineTrimmer.cpp \
	source/thewizardplusplus/wizard-basic-4/LetStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/LanguageElements.cpp \
	source/thewizardplusplus/wizard-basic-4/LabelStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/IfStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/GoToStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/GnuAssembler.cpp \
	source/thewizardplusplus/wizard-basic-4/FunctionCallStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/ExpressionCompiler.cpp \
	source/thewizardplusplus/wizard-basic-4/EndStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/EmptyLineDeleter.cpp \
	source/thewizardplusplus/wizard-basic-4/DefineStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/DeclareFunctionStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/CompilerConsoleParameters.cpp \
	source/thewizardplusplus/wizard-basic-4/Compiler.cpp \
	source/thewizardplusplus/wizard-basic-4/CommentDeleter.cpp \
	source/thewizardplusplus/wizard-basic-4/CodeLines.cpp \
	source/thewizardplusplus/wizard-basic-4/AssemblerModule.cpp \
	source/thewizardplusplus/wizard-basic-4/AssemblerMnemonic.cpp \
	source/thewizardplusplus/wizard-basic-4/AssemblerCode.cpp \
	source/thewizardplusplus/wizard-basic-4/Assembler.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownStatement.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownExpressionToken.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnknownCommandLineOption.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UndefinedVariable.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UndefinedFunction.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/UnableToOpenSourceFile.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/SeparatorNotFound.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedOpeningBracket.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedFunctionArgumentSeparatorOrOpeningBracket.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/MissedClosingBracket.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/LabelConflictWithOtherLabel.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/LabelConflictWithConditionalJumps.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidStringFormat.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidNumberOfCodeLineParts.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/InvalidFunctionIdentifier.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/IfWithoutEnd.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/IdentifierConflictWithVariable.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/IdentifierConflictWithFunction.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/EndWithoutIf.cpp \
	source/thewizardplusplus/wizard-basic-4/exceptions/CompileException.cpp
OTHER_FILES += \
	docs/examples/maze.ni \
	docs/to_do.txt \
	docs/grammar.txt \
	docs/examples/pi.ni \
	docs/working_log.txt \
	docs/syntax_highlighting/wizard_basic_4_kate.xml \
	docs/syntax_highlighting/wizard_basic_4_notepadpp.xml
QMAKE_CXXFLAGS += -std=c++98 -Wall -W -pedantic
